name: CI

on:
  push:
    tags: ['v*']
    branches: ['*']
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: 'agents'
          path: './agents/build/*.jar'
  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: 'agents'
          path: './agent'
  
          

      - name: Get Release Version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF_NAME#v}"

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: ${{ steps.version.outputs.version }}
          draft: false
          account bada_pankha
          fail_on_unmatched_files: true
          files: './agents/*
          account' bada_pankha
